#!/usr/bin/env python3

#######################################
#     Keybindings image generator     #
# Fork of Qtile's gen-keybinding-img  #
#######################################

import getopt
import json
import os
import sys
from PIL import Image
from types import SimpleNamespace

import cairocffi as cairo
from cairocffi import ImageSurface

this_dir = os.path.dirname(__file__)
base_dir = os.path.abspath(os.path.join(this_dir, ".."))
sys.path.insert(0, base_dir)

BUTTON_NAME_Y = 65
BUTTON_NAME_X = 10

COMMAND_Y = 20
COMMAND_X = 10

LEGEND = ["Modifiers", "Layout", "Screen", "Group", "Window", "Other"]

CUSTOM_KEYS = {
    "backspace": 2,
    "tab": 1.5,
    "capslock": 1.61,
    "\\": 1.5,
    "return": 2.45,
    "shift": 2,
    "space": 6,
    "Modifiers": 1.1,
    "FN_KEYS": 1.15,
}

KEY_MAP = {
    "grave": "`",
    "semicolon": ";",
    "slash": "/",
    "backslash": "\\",
    "comma": ",",
    "period": ".",
    "bracketleft": "[",
    "bracketright": "]",
    "quote": "'",
    "apostrophe": "'",
    "minus": "-",
    "equals": "=",
    "equal": "=",
}

NAME_MAP = {
    "tab": "Tab",
    "backspace": "Backspace",
    "capslock": "Caps Lock",
    "return": "Return",
    "shift": "Shift",
    "control": "Control",
    "space": "Space",
    "print": "Print",
    "scroll": "Scroll",
    "pause": "Pause",
    "delete": "Del",
    "insert": "Ins",
    "home": "Home",
    "end": "End",
    "pgup": "PgUp",
    "pageup": "PgUp",
    "pgdn": "PgDn",
    "pgdown": "PgDn",
    "pagedown": "PgDn",
    "mod1": "Alt",
    "mod4": "Super",
    "up": "↑",
    "left": "←",
    "down": "↓",
    "right": "→",
    "button1": "Button1",
    "button2": "Button2",
    "button3": "Button3",
    "xf86monbrightnessup": "MonBright ↑",
    "xf86monbrightnessdown": "MonBright ↓",
    "xf86kbdlightonoff": "KeyLite",
    "xf86kbdbrightnessup": "KeyBright ↑",
    "xf86kbdbrightnessdown": "KeyBright ↓",
    "xf86standby": "Standby",
    "xf86audiolowervolume": "Volume ↓",
    "xf86audiomute": "Mute",
    "xf86audioraisevolume": "Volume ↑",
    "xf86audioplay": "Play Media",
    "xf86audiostop": "Stop Media",
    "xf86audioprev": "Prev Media",
    "xf86audionext": "Next Media",
    "xf86homepage": "Web Home",
    "xf86mail": "Mail",
    "xf86start": "Start",
    "xf86search": "Search",
    "xf86audiorecord": "Record",
    "xf86calculator": "Calc",
    "xf86memo": "Memo",
    "xf86todolist": "Todo",
    "xf86calendar": "Calendar",
    "xf86powerdown": "Shutdown",
    "xf86contrastadjust": "Contrast",
    "xf86rockerup": "Rocker ↑",
    "xf86rockerdown": "Rocker ↓",
    "xf86rockerenter": "Rocker",
    "xf86back": "Back",
    "xf86forward": "Forward",
    "xf86stop": "Stop",
    "xf86refresh": "Refresh",
    "xf86poweroff": "Shutdown",
    "xf86wakeup": "WakeUp",
    "xf86eject": "Eject",
    "xf86screensaver": "Screensaver",
    "xf86www": "Web",
    "xf86sleep": "Sleep",
    "xf86favorites": "Bookmarks",
    "xf86audiopause": "Pause Audio",
    "xf86audiomedia": "Audio Media",
    "xf86mycomputer": "My Computer",
    "xf86shop": "Shop",
    "xf86history": "History",
    "xf86openurl": "OpenURL",
    "xf86addfavorite": "Add Bookmark",
    "xf86hotlinks": "Bookmarks",
    "xf86brightnessadjust": "Brightness",
    "xf86finance": "Finance",
    "xf86launch0": "Launch 1",
    "xf86launch1": "Launch 2",
    "xf86launch2": "Launch 3",
    "xf86launch3": "Launch 4",
    "xf86launch4": "Launch 5",
    "xf86launch5": "Launch 6",
    "xf86launch6": "Launch 7",
    "xf86launch7": "Launch 8",
    "xf86launch8": "Launch 9",
    "xf86launch9": "Launch 10",
    "xf86launcha": "Launch 11",
    "xf86launchb": "Launch 12",
    "xf86launchc": "Launch 13",
    "xf86launchd": "Launch 14",
    "xf86launche": "Launch 15",
    "xf86launchf": "Launch 16",
    "xf86applicationleft": "Prev App",
    "xf86applicationright": "Next App",
    "xf86book": "Book",
    "xf86cd": "CD",
    "xf86calculater": "Calc",
    "xf86clear": "Clear",
    "xf86close": "Close",
    "xf86copy": "Copy",
    "xf86cut": "Cut",
    "xf86display": "Display",
    "xf86documents": "Documents",
    "xf86excel": "Excel",
    "xf86explorer": "Explorer",
    "xf86game": "Game",
    "xf86go": "Go",
    "xf86itouch": "iTouch",
    "xf86logoff": "Logoff",
    "xf86market": "Market",
    "xf86meeting": "Meeting",
    "xf86menukb": "Menu KB",
    "xf86menupb": "Menu PB",
    "xf86mysites": "MySites",
    "xf86new": "New",
    "xf86news": "News",
    "xf86officehome": "Office Home",
    "xf86open": "Open",
    "xf86option": "Option",
    "xf86paste": "Paste",
    "xf86phone": "Phone",
    "xf86q": "Q",
    "xf86reply": "Reply",
    "xf86reload": "Reload",
    "xf86rotatewindows": "RotateWindows",
    "xf86rotationpb": "Rotation PB",
    "xf86rotationkb": "Rotation KB",
    "xf86save": "Save",
    "xf86scrollup": "ScrollUp",
    "xf86scrolldown": "ScrollDown",
    "xf86scrollclick": "Scroll Click",
    "xf86send": "Send",
    "xf86spell": "Spell",
    "xf86splitscreen": "Split Screen",
    "xf86support": "Support",
    "xf86taskpane": "Task Pane",
    "xf86terminal": "Terminal",
    "xf86tools": "Tools",
    "xf86travel": "Travel",
    "xf86userpb": "User PB",
    "xf86user1kb": "User1 KB",
    "xf86user2kb": "User2 KB",
    "xf86video": "Video",
    "xf86wheelbutton": "Wheel Button",
    "xf86word": "Word",
    "xf86xfer": "Xfer",
    "xf86zoomin": "Zoom ↑",
    "xf86zoomout": "Zoom ↓",
    "xf86away": "Away",
    "xf86messenger": "Messenger",
    "xf86webcam": "WebCam",
    "xf86mailforward": "Mail Forward",
    "xf86pictures": "Pictures",
    "xf86music": "Music",
    "xf86battery": "Battery",
    "xf86bluetooth": "Bluetooth",
    "xf86wlan": "WLAN",
    "xf86uwb": "UWB",
    "xf86audioforward": "Audio Fwd",
    "xf86audiorepeat": "Audio Repeat",
    "xf86audiorandomplay": "Audio Random",
    "xf86subtitle": "Subtitle",
    "xf86audiocycletrack": "Audio Cycle",
    "xf86cycleangle": "Cycle Angle",
    "xf86frameback": "Prev Frame",
    "xf86frameforward": "Next Frame",
    "xf86time": "Time",
    "xf86select": "Select",
    "xf86view": "View",
    "xf86topmenu": "Top Menu",
    "xf86red": "Red",
    "xf86green": "Green",
    "xf86yellow": "Yellow",
    "xf86blue": "Blue",
    "xf86suspend": "Suspend",
    "xf86hibernate": "Hibernate",
    "xf86touchpadtoggle": "Toggle Touchpad",
    "xf86touchpadon": "Touchpad On",
    "xf86touchpadoff": "Touchpad Off",
    "xf86audiomicmute": "Mic Mute",
    "xf86keyboard": "Keyboard",
    "xf86switch_vt_1": "VT 1",
    "xf86switch_vt_2": "VT 2",
    "xf86switch_vt_3": "VT 3",
    "xf86switch_vt_4": "VT 4",
    "xf86switch_vt_5": "VT 5",
    "xf86switch_vt_6": "VT 6",
    "xf86switch_vt_7": "VT 7",
    "xf86switch_vt_8": "VT 8",
    "xf86switch_vt_9": "VT 9",
    "xf86switch_vt_10": "VT 10",
    "xf86switch_vt_11": "VT 11",
    "xf86switch_vt_12": "VT 12",
    "xf86ungrab": "Ungrab",
    "xf86cleargrab": "Clear Grab",
    "xf86next_vmode": "Next VMode",
    "xf86prev_vmode": "Prev VMode",
    "xf86logwindowtree": "Log Win Tree",
    "xf86loggrabinfo": "Log Grab Info"
}

class Button:
    def __init__(self, key, x, y, width, height):
        self.key = key
        self.x = x
        self.y = y
        self.width = width
        self.height = height


class Pos:
    WIDTH = 78
    HEIGHT = 70
    GAP = 5

    def __init__(self, x, y):
        self.x = x
        self.row_x = x
        self.y = y
        self.custom_width = {}
        for i, val in CUSTOM_KEYS.items():
            self.custom_width[i] = val * self.WIDTH

    def get_pos(self, name):
        if name in self.custom_width:
            width = self.custom_width[name]
        else:
            width = self.WIDTH

        info = Button(name, self.x, self.y, width, self.HEIGHT)

        self.x = self.x + self.GAP + width

        return info

    def skip_x(self, times=1):
        self.x = self.x + self.GAP + times * self.WIDTH

    def next_row(self):
        self.x = self.row_x
        self.y = self.y + self.GAP + self.HEIGHT


class KeyboardPNGFactory:
    def __init__(self, modifiers, keys):
        self.keys = keys
        self.modifiers = modifiers.split("-")
        self.key_pos = self.calculate_pos(20, 140)

    def rgb_red(self, context):
        if dark_mode == 1:
            context.set_source_rgb(0.5431372549, 0.0725490196, 0.0725490196)
        else:
            context.set_source_rgb(0.8431372549, 0.3725490196, 0.3725490196)

    def rgb_grey(self, context):
        if dark_mode == 1:
            context.set_source_rgb(0.3862745098, 0.3862745098, 0.3862745098)
        else:
            context.set_source_rgb(0.6862745098, 0.6862745098, 0.6862745098)

    def rgb_green(self, context):
        if dark_mode == 1:
            context.set_source_rgb(0.3862745098, 0.3862745098, 0)
        else:
            context.set_source_rgb(0.6862745098, 0.6862745098, 0)

    def rgb_yellow(self, context):
        if dark_mode == 1:
            context.set_source_rgb(0.7, 0.3862745098, 0)
        else:
            context.set_source_rgb(1, 0.6862745098, 0)

    def rgb_cyan(self, context):
        if dark_mode == 1:
            context.set_source_rgb(0.2137254902, 0.3784313725, 0.3784313725)
        else:
            context.set_source_rgb(0.5137254902, 0.6784313725, 0.6784313725)

    def rgb_violet(self, context):
        if dark_mode == 1:
            context.set_source_rgb(0.531372549, 0.2215686275, 0.3784313725)
        else:
            context.set_source_rgb(0.831372549, 0.5215686275, 0.6784313725)

    def calculate_pos(self, x, y):
        pos = Pos(x, y)

        key_pos = {}
        for c in "`1234567890-=":
            key_pos[c] = pos.get_pos(c)

        key_pos["backspace"] = pos.get_pos("backspace")
        pos.next_row()

        key_pos["tab"] = pos.get_pos("tab")
        for c in "qwertyuiop[]\\":
            key_pos[c] = pos.get_pos(c)
        pos.next_row()

        key_pos["capslock"] = pos.get_pos("capslock")
        #pos.skip_x(1.6)
        for c in "asdfghjkl;'":
            key_pos[c] = pos.get_pos(c)
        key_pos["return"] = pos.get_pos("return")
        pos.next_row()

        key_pos["shift"] = pos.get_pos("shift")
        for c in "zxcvbnm,./":
            key_pos[c] = pos.get_pos(c)
        pos.skip_x(0.94)
        key_pos["up"] = pos.get_pos("up")
        pos.next_row()

        key_pos["control"] = pos.get_pos("control")
        key_pos["mod4"] = pos.get_pos("mod4")
        key_pos["mod1"] = pos.get_pos("mod1")
        key_pos["space"] = pos.get_pos("space")
        key_pos["print"] = pos.get_pos("print")
        key_pos["scroll"] = pos.get_pos("scroll")
        key_pos["pause"] = pos.get_pos("pause")
        pos.skip_x(0.13)
        key_pos["left"] = pos.get_pos("left")
        key_pos["down"] = pos.get_pos("down")
        key_pos["right"] = pos.get_pos("right")

        pos.next_row()
        pos.skip_x(12.58)
        key_pos["insert"] = pos.get_pos("insert")
        key_pos["home"] = pos.get_pos("home")
        key_pos["pgup"] = pos.get_pos("pgup")
        #key_pos["button4"] = pos.get_pos("button4")
        #key_pos["button5"] = pos.get_pos("button5")
        #key_pos["button6"] = pos.get_pos("button6")

        pos.next_row()
        if [i for i in keys.values() if i.key[:4] == "xf86"]:
            key_pos["FN_KEYS"] = pos.get_pos("FN_KEYS")
            pos.skip_x(11.36)
        else:
            pos.skip_x(12.58)
        #key_pos["FN_KEYS"] = pos.get_pos("FN_KEYS")
        #pos.skip_x(11.36)
        key_pos["delete"] = pos.get_pos("delete")
        key_pos["end"] = pos.get_pos("end")
        key_pos["pgdn"] = pos.get_pos("pgdn")

        pos.next_row()
        if show_legend == 1:
            if show_legend == 1:
                for legend in LEGEND:
                    key_pos[legend] = pos.get_pos(legend)
            pos.skip_x(6.09)
        else:
            pos.skip_x(12.58)
        key_pos["button1"] = pos.get_pos("button1")
        key_pos["button2"] = pos.get_pos("button2")
        key_pos["button3"] = pos.get_pos("button3")


        return key_pos

    def add_logo(self, context):
        max_height = 100
        x = 20
        y = 25
        if not os.path.exists(logo_img):
            print(f"Error: Logo file '{logo_img}' does not exist.")
            sys.exit(1)

        context.save()
        logo = ImageSurface.create_from_png(logo_img)
        h = logo.get_height()
        if h > max_height:
            scale_factor = max_height / h
        else:
            scale_factor = 1.0
            if h < max_height:
                y += (max_height - h) / 2

        context.scale(scale_factor, scale_factor)
        context.set_source_surface(logo, x, y)
        context.paint()
        context.restore()

        return logo.get_width() * scale_factor, logo.get_height() * scale_factor

    def render(self, filename):
        surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, 1280, 800)
        context = cairo.Context(surface)
        with context:
            if dark_mode == 1:
                context.set_source_rgb(0, 0, 0)
            else:
                context.set_source_rgb(1, 1, 1)
            context.paint()

        if dark_mode == 1:
            context.set_source_rgb(1, 1, 1)
        else:
            context.set_source_rgb(0, 0, 0)

        move_x = 25
        if show_modifiers == 1:
            move_y = 70
        else:
            move_y = 85
        if logo_img:
            img_w, _ = self.add_logo(context)
            move_x += img_w + 10
            move_y += 0

        context.move_to(move_x, move_y)
        context.set_font_size(28)
        if app_title:
            context.show_text(f"Keybindings for {app_title}")
        else:
            context.show_text("Keybindings")

        if show_modifiers == 1:
            context.move_to(move_x, move_y + 20)
            context.set_font_size(18)
            if len([i for i in self.modifiers if i]):
                modifiers = " + ".join(self.modifiers)
                modifiers = modifiers.replace('mod4', NAME_MAP['mod4'])
                modifiers = modifiers.replace('mod1', NAME_MAP['mod1'])
                modifiers = modifiers.replace('shift', NAME_MAP['shift'])
                modifiers = modifiers.replace('control', NAME_MAP['control'])
                context.show_text("Modifiers: " + modifiers)
            else:
                context.show_text("No modifiers used.")

        for i in self.key_pos.values():
            if i.key in ["FN_KEYS"]:
                continue

            self.draw_button(context, i.key, i.x, i.y, i.width, i.height)

        # draw functional
        fn = [i for i in keys.values() if i.key[:4] == "xf86"]
        if len(fn):
            fn_pos = self.key_pos["FN_KEYS"]
            x = fn_pos.x
            for i in fn:
                self.draw_button(context, i.key, x, fn_pos.y, fn_pos.width, fn_pos.height)
                x += Pos.GAP + 12 + Pos.WIDTH

        # draw mouse base
        context.rectangle(1006, 735, 244, 40)
        if dark_mode == 1:
            context.set_source_rgb(1, 1, 1)
        else:
            context.set_source_rgb(0, 0, 0)
        context.stroke()
        context.set_font_size(28)
        context.move_to(1076, 765)
        context.show_text("Mouse")

        surface.write_to_png(filename)

    def draw_button(self, context, key, x, y, width, height):
        fn = False
        if key[:4] == "xf86":
            fn = True

        if key in LEGEND:
            if key == "Modifiers":
                self.rgb_red(context)
            elif key == "Group":
                self.rgb_green(context)
            elif key == "Layout":
                self.rgb_cyan(context)
            elif key == "Window":
                self.rgb_yellow(context)
            elif key == "Screen":
                self.rgb_grey(context)
            else:
                self.rgb_violet(context)
            context.rectangle(x, y, width, height)
            context.fill()

        if key in self.modifiers:
            context.rectangle(x, y, width, height)
            self.rgb_red(context)
            context.fill()

        if key in self.keys:
            k = self.keys[key]
            context.rectangle(x, y, width, height)
            self.set_key_color(context, k)
            context.fill()

            self.show_multiline(context, x + COMMAND_X, y + COMMAND_Y, k)

        context.rectangle(x, y, width, height)
        if dark_mode == 1:
            context.set_source_rgb(1, 1, 1)
        else:
            context.set_source_rgb(0, 0, 0)
        context.stroke()

        if fn:
            context.set_font_size(10)
        else:
            context.set_font_size(14)

        context.move_to(x + BUTTON_NAME_X, y + BUTTON_NAME_Y)
        key_text = key
        if key_text.lower() in NAME_MAP.keys():
            key_text = NAME_MAP[key_text.lower()]
        try:
            if legend_map and key_text in legend_map.keys():
                key_text = legend_map[key_text]
        except:
            print(f"Error: Invalid Legend Map ({legend_map})")
            sys.exit(2)
        context.show_text(key_text)

    def show_multiline(self, context, x, y, key):
        """Cairo doesn't support multiline. Added with word wrapping."""
        c_width = 14
        x = x - 5
        width_padding = 2
        if key.key in CUSTOM_KEYS:
            c_width *= CUSTOM_KEYS[key.key]

        context.set_font_size(10)
        if dark_mode == 1:
            context.set_source_rgb(1, 1, 1)
        else:
            context.set_source_rgb(0, 0, 0)
        context.move_to(x, y)
        words = key.command.split(" ")
        words.reverse()
        printable = last_word = words.pop()
        while len(words):
            last_word = words.pop()
            if len(printable + " " + last_word) < c_width - width_padding:
                printable += " " + last_word
                continue

            context.show_text(printable)
            y += 10
            context.move_to(x, y)
            printable = last_word

        if last_word is not None:
            context.show_text(printable)

    def set_key_color(self, context, key):
        if key.scope == "group":
            self.rgb_green(context)
        elif key.scope == "layout":
            self.rgb_cyan(context)
        elif key.scope == "window":
            self.rgb_yellow(context)
        elif key.scope == "screen":
            self.rgb_grey(context)
        else:
            self.rgb_violet(context)

def get_kb_map(command,input_file):
    import subprocess

    if command:
        result = subprocess.run(command.split(" "), capture_output=True, text=True, check=True)
        bindlist = json.loads(result.stdout)
    else:
        try:
            with open(input_file, 'r') as file:
                bindlist = json.load(file)
        except FileNotFoundError:
            print(f"File not found ({input_file})")
            sys.exit(2)
        except json.JSONDecodeError as e:
            print(f"Invalid JSON format: {e}")
            sys.exit(2)
        except Exception as e:
            print(f"Error loading JSON: {e}")
            sys.exit(2)

    kb_map = {}

    for binding in bindlist:
        #print(binding['key'], binding['description'])
        mod = binding['modifiers']
        if mod not in kb_map:
            kb_map[mod] = {}

        key = str(binding['key'].lower())
        if key in KEY_MAP.keys():
            key = KEY_MAP[key]
        if not "description" in binding.keys():
            binding['description'] = ""
        if not "scope" in binding.keys():
            binding['scope'] = ""
        data = { 'command': binding['description'], 'key': key, 'scope': binding['scope'] }
        kb_map[mod][data['key']] = SimpleNamespace(**data)

    return kb_map

help_doc = """
usage: gen-keybinding-img [-h] [-d] [-L] [-M] -c COMMAND|-j JSONFILE
                             [-o OUTPUT_DIR] [-l LOGO_FILE] [-t TITLE] [-k LEGEND_MAP]

Keybindings image generator

optional arguments:
    -h, --help                show this help message and exit
    -d, --dark                create dark mode images
    -L, --no-legend           do not show Legend
    -M, --no-modifiers-list   do not show modifiers list
    -c COMMAND, --config COMMAND
                              use specified command to get keybindings
                              output must be in json with the following fields:
                                  key, command, description, modifiers (e.g. "mod4-control-shift"), scope
    -j JSONFILE, --json-file JSONFILE
                              use specified json file to get keybindings
                              file must have the following fields per binding:
                                  key, command, description, modifiers (e.g. "mod4-control-shift"), scope
    -o OUTPUT_DIR, --output-dir OUTPUT_DIR
                              set directory to export all images to
    -l LOGO_FILE, --logo LOGO_FILE
                              set logo file to use
    -t APP_TITLE, --title APP_TITLE
                              set application title for keybindings
    -k LEGEND_MAP, --legend-map LEGEND_MAP
                              a dict mapping legend labels to new names
"""
if __name__ == "__main__":
    keys_command = None
    keys_file = None
    output_dir = ""
    logo_img = ""
    app_title = ""
    dark_mode = 0
    show_legend = 1
    show_modifiers = 1
    legend_map = None
    try:
        opts, args = getopt.getopt(sys.argv[1:], "hdLMc:j:o:l:t:k:", ["help=", "dark=", "legend=", "modifiers=", "legend-map=", "command=", "json-file=", "output-dir=", "logo=", "title="])

    except getopt.GetoptError:
        print(help_doc)
        sys.exit(2)

    for opt, arg in opts:
        if opt in ("-h", "--help"):
            print(help_doc)
            sys.exit()
        elif opt in ("-L", "--no-legend"):
            show_legend = 0
        elif opt in ("-M", "--no-modifiers-list"):
            show_modifiers = 0
        elif opt in ("-d", "--dark"):
            dark_mode = 1
        elif opt in ("-c", "--command"):
            keys_command = arg
        elif opt in ("-j", "--json-file"):
            keys_file = arg
        elif opt in ("-o", "--output-dir"):
            output_dir = arg
        elif opt in ("-l", "--logo"):
            logo_img = arg
        elif opt in ("-t", "--title"):
            app_title = arg
        elif opt in ("-k", "--legend-map"):
            try:
                legend_map = json.loads(arg)
            except:
                print(f"Error: Invalid Legend Map ({legend_map})")
                sys.exit(2)

    if not keys_command and not keys_file:
        print("Error: Command must be specified with -c OR JSON file must be specified with -j")
        print(help_doc)
        sys.exit(2)

    kb_map = get_kb_map(keys_command, keys_file)
    for modifier, keys in kb_map.items():
        if not modifier:
            filename = "no_modifier.png"
        else:
            fname = modifier.replace('mod4', NAME_MAP['mod4'])
            fname = fname.replace('mod1', NAME_MAP['mod1'])
            fname = fname.replace('shift', NAME_MAP['shift'])
            fname = fname.replace('control', NAME_MAP['control'])
            filename = f"{fname}.png"

        output_file = os.path.abspath(os.path.join(output_dir, filename))
        f = KeyboardPNGFactory(modifier, keys)
        f.render(output_file)
