#!/usr/bin/python3

import json
import re
import subprocess

result = subprocess.run(['hyprctl', '--instance', '0', '-j', 'binds'],
                        capture_output=True, text=True, check=True)

modmasks = {
    0: "",
    1: "shift",
    4: "control",
    5: "control-shift",
    8: "mod1",
    9: "mod1-shift",
    12: "control-mod1",
    13: "control-mod1-shift",
    64: "mod4",
    65: "mod4-shift",
    68: "mod4-control",
    69: "mod4-control-shift",
    72: "mod4-mod1",
    73: "mod4-mod1-shift",
    76: "mod4-control-mod1",
    77: "mod4-control-mod1-shift"
}
binds = json.loads(result.stdout)

keybindings = []
for bind in binds:
    if not bind['description']:
        continue
    scope = "other"
    dispatch = bind['dispatcher']
    if "monitor" in dispatch and dispatch != "focusworkspaceoncurrentmonitor":
        scope = "screen"
    elif "workspace" in dispatch:
        scope = "workspace"
    elif "window" in dispatch or "movefocus" in dispatch or "cyclenext" in dispatch or "togglesplit" in dispatch or "togglefloating" in dispatch or "killactive" in dispatch or "fullscreen" in dispatch or (dispatch == "mouse" and "window" in bind['arg']):
        scope = "window"
    elif "pseudo" in dispatch:
        scope = "layout"
    elif dispatch == "exec":
        scope = "other"
    if re.match(r'^[A-Z]$', bind['key']):
        bind['key'] = bind['key'].lower()
    elif bind['key'] == "mouse:272":
        bind['key'] = "Button1"
    elif bind['key'] == "mouse:274":
        bind['key'] = "Button2"
    elif bind['key'] == "mouse:273":
        bind['key'] = "Button3"
    keybindings.append({
        'key': str(bind['key']),
        'command': f"{dispatch} {bind['arg']}" if bind['arg'] else dispatch,
        'description': bind['description'],
        'modifiers': modmasks[bind['modmask']],
        'scope': scope
    })
    #print(bind)
    #sys.exit(0)

#for key in c.keys:
#    keybindings.append({
#      'key': str(key.key).lower(),
#      'command': key.commands[0].name + " " + key.commands[0].args[0] if len(key.commands[0].args) and isinstance(key.commands[0].args[0], str) else key.commands[0].name,
#      'description': key.desc,
#      'modifiers': "-".join(key.modifiers),
#      'scope': key.commands[0].selectors[0][0] if len(key.commands[0].selectors) else None,
#    })

print(json.dumps(keybindings))
