#!/usr/bin/env bash

declare -a modmasks
modmasks[0]=""
modmasks[1]="shift"
modmasks[4]="control"
modmasks[5]="control-shift"
modmasks[8]="mod1"
modmasks[9]="mod1-shift"
modmasks[12]="control-mod1"
modmasks[13]="control-mod1-shift"
modmasks[64]="mod4"
modmasks[65]="mod4-shift"
modmasks[68]="mod4-control"
modmasks[69]="mod4-control-shift"
modmasks[72]="mod4-mod1"
modmasks[73]="mod4-mod1-shift"
modmasks[76]="mod4-control-mod1"
modmasks[77]="mod4-control-mod1-shift"

get_niri_includes() {
  local cfg=${1:-$HOME/.config/niri/config.kdl}
  local arr=()

  # Get list of includes from the niri configuration directory
  cfg=$(cd "$HOME"/.config/niri 2> /dev/null && realpath "$cfg" 2> /dev/null || return 1)
  mapfile -t arr < \
    <(awk '/^\s*include\s/{sub(/^\s*include\s+(optional=[^\s]+)\s+"/,"");sub(/"$/,"");print}' "$cfg")
  niri_configs+=("$(realpath "$cfg")")
  for file in "${arr[@]}"; do
    get_niri_includes "$file"
  done
}

parse_keybind() {
  (( $# < 1 )) && return 1
  local line="$*" keyname key key_combo keybinding desc cmd parts=() modmask=0 scope

  # Trim whitespace and remove "binds {" from the beginning
  line=${line#"${line%%[! ]*}"}
  line=${line%"${line##*[! ]}"}
  line=${line#binds \{}
  line=${line#"${line%%[! ]*}"}

  # The key is the first part before any spaces
  key_combo=${line%% *}
  # Split parts of key_combo
  IFS=+ read -ra parts <<< "$key_combo"
  for key in "${parts[@]}"; do
    case $key in
      [Ss]hift)                modmask=$((modmask+1)) ;;
      [Cc]ontrol|[Cc]trl)      modmask=$((modmask+4)) ;;
      [Aa]lt|[Mm]od1)          modmask=$((modmask+8)) ;;
      [Ss]uper|[Mm]od4|[Mm]od) modmask=$((modmask+64)) ;;
      *) keybinding=${key/Page_Up/PgUp} ; keybinding=${keybinding/Page_Down/PgDn} ;;
    esac
  done
  keyname=$(echo "${modmasks[$modmask]:+${modmasks[$modmask]}-}$keybinding" | tr '[:upper:]' '[:lower:]')
  # Save keylist and modlist for key_combo
  keylist[$keyname]=$keybinding
  modlist[$keyname]=${modmasks[$modmask]}

  # If hotkey-overlay-title is defined, grab it
  if [[ "$line" == *" hotkey-overlay-title=\""* ]]; then
    desc=${line#* hotkey-overlay-title=\"}
    desc=${desc%%\"*}
  fi

  # The command is the part between { ... }
  cmd=${line##*\{}
  cmd=${cmd# }
  cmd=${cmd%%\}*}
  cmd=${cmd% }
  cmd=${cmd%;}
  cmd="${cmd//\\/\\\\}"
  cmd="${cmd//\"/\\\"}"
  cmdlist[$keyname]=$cmd

  local newdesc=() word
  if [[ -z "$desc" ]]; then
    if [[ "$cmd" == spawn* ]]; then
      desc=${cmd#spawn}
      desc=${desc#-sh}
      desc=${desc# \\\"}
      desc=${desc%\\\"}
    else
      desc=${cmd//-/ }
      newdesc=()
      for word in $desc; do
        declare -u first
        first=${word:0:1}
        newdesc+=("${first}${word:1}")
      done
      desc="${newdesc[@]}"
    fi
  fi

  desc=${desc#\$HOME/.config/niri/scripts/}
  desc=${desc/@DEFAULT_AUDIO_SINK@/speakers}
  desc=${desc/@DEFAULT_AUDIO_SOURCE@/mic}
  desc=${desc/ or /\/}
  desc=${desc/ Or /\/}
  desc=${desc/Workspace/WS}
  desc=${desc//\\\"/}
  desc=${desc//\"/}
  desc=${desc//  / }
  desclist[$keyname]=$desc

  case "$desc" in
    *[Mm]ove[" "-][Ww]indow*|*[Mm]ove[" "-][Cc]olumn*|*"Focus Next Column"*|*"Focus Previous Column"*)
      scope=window
      ;;
    *Move[" "-]WS*|*Move[" "-][Ww]orkspace*)
      scope=group
      ;;
    *[Ll]ayout*|*[Ff]ullscreen*|*[Ff]loating*|*[Ss]plit*|*focus" "mode*|*Focus*Float/Tile)
      scope=layout
      ;;
    *[Mm]onitor*|*[Ss]creen*|*[Oo]utput*)
      scope=screen
      ;;
    *[Ww]orkspace*|*WS*|scratchpad" "show*|Show" "[Ss]cratchpad*)
      scope=group
      ;;
    *[Ww]indow*|*[Cc]olumn*|*[Ff]ocus*|kill|move" "scratchpad*|resize*|set-column-width|set-window-width|set-window-height|Resize" "[Ww]indow*|move" "*)
      scope=window
      ;;
    *)
      scope=other
      ;;
  esac
  scopelist[$keyname]=$scope
}

main() {
  niri_configs=()
  get_niri_includes "$1"

  declare -A keylist cmdlist desclist modlist scopelist

  in_binds=false
  for file in "${niri_configs[@]}"; do
    i=0
    while IFS= read -r line; do
      ((i++))
      # Strip leading and trailing spaces
      line=${line%%//*}
      line=${line#"${line%%[! ]*}"}
      line=${line%"${line##*[! ]}"}

      [[ "$line" == *" hotkey-overlay-title=null "* ]] && continue
      # Look for lines that have "binds { ... }"
      [[ "$line" =~ ^binds[[:space:]]+\{.*[^[:space:]]+.*\}$ ]] && parse_keybind "$line" && continue

      # Start looking for binds with "binds {"
      [[ "$line" =~ ^binds[[:space:]]+\{[[:space:]]*\}$ ]] && continue
      [[ "$line" =~ ^binds[[:space:]]+\{$ ]] && in_binds=true && continue

      # Stop looking for binds with "}"
      [[ "$line" =~ ^\}$ ]] && in_binds=false && continue

      # If not looking for binds, continue
      $in_binds || continue

      # If line is empty or line starts with a comment, continue
      [[ -z "$line" ]] && continue

      parse_keybind "$line"
    done < "$file"
  done

  # Generate JSON output
  jsons=()
  for key in "${!keylist[@]}"; do
    printf -v item '{ "key": "%s", "command": "%s", "description": "%s", "modifiers": "%s", "scope": "%s" }' \
      "${keylist[$key]}" "${cmdlist[$key]}" "${desclist[$key]}" "${modlist[$key]}" "${scopelist[$key]}"
    jsons+=("$item")
  done
  json=$(IFS=,; echo "[${jsons[*]}]")

  # Check with python json to ensure that the JSON is valid
  if echo "$json" | python3 -c "import sys, json; json.load(sys.stdin)" 2> /dev/null; then
    echo "$json"
  else
    echo "Error: Could not generate valid json" >&2
    exit 1
  fi
}

if ! (return 2> /dev/null); then
  main "$@"
fi
